insert into crimes_uk_crimes_with_poi (
	crime_id,
	number_poi,
	number_poi_community,
	number_poi_food_and_drink,
	number_poi_fuel,
	number_poi_atm,
	number_poi_transport,
	number_poi_motorcycle_dealership,
	number_poi_wifi_hotspot,
	number_poi_shopping_supermarkets,
	number_poi_special_interest,
	number_poi_shopping_others,
	number_poi_banks,
	number_poi_sports_center,
	number_poi_car_dealership,
	number_poi_commercial_site,
	number_poi_association,
	number_poi_car_parts_supplier,
	number_poi_builder_and_diy_supplies,
	number_poi_accommodation,
	number_poi_attraction,
	number_poi_pharmacy,
	number_poi_healthcare,
	number_poi_landmark,
	number_poi_public_service_buildings,
	number_poi_shopping_consumer_electrics,
	number_poi_entertainment,
	number_poi_car_servicing,
	number_poi_building_society,
	number_poi_bookshop,
	number_poi_truck_dealership,
	number_poi_holiday_park,
	number_poi_government_agency,
	number_poi_vehicle_hire,
	number_poi_car_auction,
	number_poi_caravan_dealership,
	number_poi_courier,
	number_poi_estate_agent
)
select
	c.id,
	count(*),
	sum(case when p.category = 'Community' then 1 else 0 end),
	sum(case when p.category = 'Food and drink' then 1 else 0 end),
	sum(case when p.category = 'Fuel' then 1 else 0 end),
	sum(case when p.category = 'ATM' then 1 else 0 end),
	sum(case when p.category = 'Transport' then 1 else 0 end),
	sum(case when p.category = 'Motorcycle Dealership' then 1 else 0 end),
	sum(case when p.category = 'Wifi hotspot' then 1 else 0 end),
	sum(case when p.category = 'Shopping supermarkets' then 1 else 0 end),
	sum(case when p.category = 'Special Interest' then 1 else 0 end),
	sum(case when p.category = 'Shopping others' then 1 else 0 end),
	sum(case when p.category = 'Banks' then 1 else 0 end),
	sum(case when p.category = 'Sports center' then 1 else 0 end),
	sum(case when p.category = 'Car Dealership' then 1 else 0 end),
	sum(case when p.category = 'Commercial site' then 1 else 0 end),
	sum(case when p.category = 'Association' then 1 else 0 end),
	sum(case when p.category = 'Car parts supplier' then 1 else 0 end),
	sum(case when p.category = 'Builder and DIY supplies' then 1 else 0 end),
	sum(case when p.category = 'Accommodation' then 1 else 0 end),
	sum(case when p.category = 'Attraction' then 1 else 0 end),
	sum(case when p.category = 'Pharmacy' then 1 else 0 end),
	sum(case when p.category = 'Healthcare' then 1 else 0 end),
	sum(case when p.category = 'Landmark' then 1 else 0 end),
	sum(case when p.category = 'Public service buildings' then 1 else 0 end),
	sum(case when p.category = 'Shopping consumer electrics' then 1 else 0 end),
	sum(case when p.category = 'Entertainment' then 1 else 0 end),
	sum(case when p.category = 'Car Servicing' then 1 else 0 end),
	sum(case when p.category = 'Building society' then 1 else 0 end),
	sum(case when p.category = 'Bookshop' then 1 else 0 end),
	sum(case when p.category = 'Truck Dealership' then 1 else 0 end),
	sum(case when p.category = 'Holiday park' then 1 else 0 end),
	sum(case when p.category = 'Government agency' then 1 else 0 end),
	sum(case when p.category = 'Vehicle hire' then 1 else 0 end),
	sum(case when p.category = 'Car auction' then 1 else 0 end),
	sum(case when p.category = 'Caravan Dealership' then 1 else 0 end),
	sum(case when p.category = 'Courier' then 1 else 0 end),
	sum(case when p.category = 'Estate agent' then 1 else 0 end)
from crimes_uk_crimes c, crimes_uk_poi p
where
	c.county = 'city of london'
	and ST_CONTAINS(
	    ST_MakeEnvelope(
	          c.latitude - (5.0/1110), 
	          c.longitude - (5.0/1110),
	          c.latitude + (5.0/1110), 
	          c.longitude + (5.0/1110)
	        )
	, p.geom)
group by c.id;
